[profile.default]
src = "proposals"
test = "proposals"
out = "out"
libs = ["lib"]
evm_version = "cancun"
solc = "0.8.25"

fs_permissions = [{ access = "read", path = "./"}]

[rpc_endpoints]
base = "${BASE_MAINNET_RPC_URL}"
tenderly = "${TENDERLY_FORK_RPC_URL}"

[fmt]
line_length = 80
bracket_spacing = true
number_underscore = "preserve"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
